package Group;

import Main.GuestView;
import com.google.gdata.util.ServiceException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Swing update data grup
 * @author Hendro Triokta Brianto - 13512081
 */
public class GroupJFrameEdit extends javax.swing.JFrame {

    Group g;
    private List<String> aList;
    /**
     * Creates new form GroupJFrameEdit
     * @param no_tubes
     * @param group_name
     */
    public GroupJFrameEdit(String no_tubes, String group_name) {
        initComponents();
        this.g = new Group();
        aList = new ArrayList<>();
        //viddetails = new ArrayList<>();
        g.setNo_tubes(Integer.parseInt(no_tubes));
        g.setGroup_name(group_name);
        temp_kel.setVisible(false);
        temp_tubes.setVisible(false);
        setTemp(no_tubes, group_name);
        inisialisasi();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        no_tubes = new javax.swing.JTextField();
        group_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        anggota_1 = new javax.swing.JTextField();
        anggota_2 = new javax.swing.JTextField();
        anggota_3 = new javax.swing.JTextField();
        b_update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        temp_tubes = new javax.swing.JLabel();
        temp_kel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("No Tubes");

        no_tubes.setToolTipText("");
        no_tubes.setName("no_tubes"); // NOI18N

        jLabel2.setText("Nama Kelompok");

        b_update.setText("Update");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        jLabel5.setText("Anggota 3");

        jLabel4.setText("Anggota 2");

        jLabel3.setText("Anggota 1");

        temp_tubes.setText("temp_tubes");

        temp_kel.setText("temp_kel");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anggota_1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anggota_2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anggota_3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(group_name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_tubes, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temp_kel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(temp_tubes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(b_update)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temp_tubes)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(temp_kel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_tubes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(group_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anggota_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anggota_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anggota_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(b_update)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * untuk menyimpan data yang baru diubah
     * @param evt 
     */
    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        if(!cek()){
            JOptionPane.showMessageDialog(rootPane, "Nomor Tubes dan Nama Kelompok harus diisi..!", "KatalogV Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Apa anda yakin untuk menyimpan data ini?","Warning",dialogButton);

            if(dialogResult == JOptionPane.YES_OPTION){
                try {
                    g.setNo_tubes(Integer.parseInt(no_tubes.getText()));
                    g.setGroup_name(group_name.getText());
                    aList.add(anggota_1.getText());
                    aList.add(anggota_2.getText());
                    aList.add(anggota_3.getText());

                    g.setMember(aList);

                    g.update(Integer.parseInt(temp_tubes.getText()), temp_kel.getText());

                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan...");
                    clean();
                    this.close();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ada Kesalahan...");
                    Logger.getLogger(GroupJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_b_updateActionPerformed

    /**
     * 
     * inisialisasi ketika form baru diaktifkan
     * @param evt 
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        final int WIDTH = screenSize.width;
        final int HEIGHT = screenSize.height;
        int lebar = (int) this.getSize().getWidth() / 2;
        int tinggi = (int) this.getSize().getHeight() / 2;
        // Setup the frame accordingly
        // This is assuming you are extending the JFrame //class
        this.setLocation((WIDTH/2) - lebar, (HEIGHT/2) - tinggi);
    }//GEN-LAST:event_formWindowActivated
 
    /**
     * 
     * Kembali ke form sebelumnya
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * 
     * pindah frame dan menutup frame ini
     */
    public void close(){
        try {
            new GuestView().setVisible(true);
        } catch (SQLException | IOException | ServiceException ex) {
            Logger.getLogger(GroupJFrameEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }
    
    /**
     * mengeset temp sebagai acuan update
     * @param no_tubes
     * @param group_name 
     */
    public void setTemp(String no_tubes, String group_name){
        temp_tubes.setText(no_tubes);
        temp_kel.setText(group_name);
    }
    
    /**
     * 
     * inisialisasi tambahan
     */
    public void inisialisasi(){
        try {
            List<String[]> groupEdit= g.GroupDataEdit();
            no_tubes.setText(groupEdit.get(0)[0]);
            group_name.setText(groupEdit.get(0)[1]);
            anggota_1.setText(groupEdit.get(0)[2]);
            anggota_2.setText(groupEdit.get(0)[3]);
            anggota_3.setText(groupEdit.get(0)[4]);
        } catch (SQLException ex) {
            Logger.getLogger(GroupJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * 
     * mengosongkan JTextFiels
     */
    public void clean(){
        no_tubes.setText("");
        group_name.setText("");
        anggota_1.setText("");
        anggota_2.setText("");
        anggota_3.setText("");
        
        aList.clear();
    }
    
    /**
     * 
     * mengecek kekosongan JTeksField
     * @return 
     */
    public boolean cek(){
        if(no_tubes.getText().equals("") || group_name.getText().equals("")){
            return false;
        }
        else{
            return true;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anggota_1;
    private javax.swing.JTextField anggota_2;
    private javax.swing.JTextField anggota_3;
    private javax.swing.JButton b_update;
    private javax.swing.JTextField group_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField no_tubes;
    private javax.swing.JLabel temp_kel;
    private javax.swing.JLabel temp_tubes;
    // End of variables declaration//GEN-END:variables
}
